FROM node:20-alpine
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN corepack enable && pnpm install --frozen-lockfile --prod

COPY server ./server

EXPOSE 3000
CMD ["node", "server/mail-server.mjs"]